name: Build and Cache

on:
  push: {}
  workflow_dispatch: {}

env:
  ATTIC_URL: ${{ secrets.ATTIC_URL }}
  ATTIC_TOKEN: ${{ secrets.ATTIC_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v30
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up attic
        run: |
          nix-env -i -f '<nixpkgs>' -A attic-client
          attic login default "$ATTIC_URL" "$ATTIC_TOKEN"
          attic use default

      - name: build hello
        run: |
          attic watch-store default:default &
          nix build
          sleep 30
