name: Build and Cache

on:
  push: {}
  workflow_dispatch: {}

env:
  ATTIC_URL: ${{ secrets.ATTIC_URL }}
  ATTIC_TOKEN: ${{ secrets.ATTIC_TOKEN }}
  ATTIC_CACHE: ${{ secrets.ATTIC_CACHE }}

jobs:
  build:
    env:
      NIX_PATH: "nixpkgs=channel:nixos-unstable"

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v30
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - uses: sgillespie/actions/attic@latest
        name: Attic cache
        with:
          endpoint: ${{ secrets.ATTIC_URL }}
          cache: ${{ secrets.ATTIC_CACHE }}
          access_token: ${{ secrets.ATTIC_TOKEN }}

      - name: build hello
        run: |
          nix build -L .\#
