name: Build and Cache

on:
  push: {}
  workflow_dispatch: {}

env:
  ATTIC_URL: ${{ secrets.ATTIC_URL }}
  ATTIC_TOKEN: ${{ secrets.ATTIC_TOKEN }}
  ATTIC_CACHE: ${{ secrets.ATTIC_CACHE }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v30
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          extra_nix_config: |
            post-build-hook = ${{ runner.temp }}/post-build.sh

      - name: Set up attic
        run: |
          # Create the post-build script
          cat <<EOF > "${{ runner.temp }}/post-build.sh"
          #!/bin/sh
          set -eufx

          echo "Uploading paths" $OUT_PATHS
          exec attic push "${{ secrets.ATTIC_CACHE }}" $OUT_PATHS
          EOF

          # Make it executable
          chmod +x "${{ runner.temp }}/post-build.sh"

          # Install Attic client
          nix-env \
            --install \
            --option post-build-hook "" # The script would fail without attic
            --file '<nixpkgs>' \
            --attr attic-client
          attic login iog "$ATTIC_URL" "$ATTIC_TOKEN"
          attic use iog:midnight



      - name: build hello
        run: |
          nix build -L .\#
